# Generated by Django 4.2.2 on 2024-08-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerId', models.CharField(max_length=150)),
                ('disable', models.BooleanField(default=False)),
                ('upTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10)),
                ('language', models.CharField(choices=[('python', 'python'), ('cpp', 'cpp'), ('c', 'c'), ('java', 'java')], max_length=10)),
                ('code', models.TextField(blank=True, null=True)),
                ('submissionTime', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, choices=[('RUN', 'Run Submission'), ('SUB', 'Submit Submission')], max_length=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PEN', 'Pending'), ('ONF', 'Output Not Found')], max_length=5, null=True)),
                ('isCorrect', models.BooleanField(default=False)),
                ('correctSubmissions', models.IntegerField(default=0)),
                ('totalSubmissions', models.IntegerField(default=0)),
                ('timeLimit', models.IntegerField(default=1)),
            ],
        ),
    ]
